# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ping-pong-mgmt

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1


# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
package:
  exclude:
    - .node_modules/**

plugins:
  - serverless-python-requirements

functions:
  handle_miss_ping:
    handler: handler.handle_miss_ping

  reader:   # function reader subscribes to read_from_bot topic
    handler: reader.read_from_bot
    events:
      - sns:
        topicName: read_from_bot
        displayName: Messages to read from slack channel

  writer:  # function writer subscribes to write_to_bot topic
    handler: writer.write_to_bot
    events:
      - sns:
        topicName: write_to_bot
        displayName: Messages to write to slack channel

  neo4j_write:
    handler: neo4j_writer.write

# this setup specifies that the handle_miss_ping function should be run
# when someone acesses the APi Gateway at miss-ping-handler via a POST request
  index:
    handler: handler.handle_miss_ping
    events:
      - http: POST miss-ping-handler