# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ping-pong-mgmt

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1


# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
package:
  exclude:
    - .node_modules/**

plugins:
  - serverless-python-requirements

functions:
  handle_miss_ping:
    handler: handler.handle_miss_ping

  want_to_play:
    handler: want_to_play.request_want_to_play
    events:
      - sns:
        topicName: request_want_to_play
        displayName: Messages to read from slack channel for want to play command

  res_want_to_play:
    handler: res_want_to_play.response_want_to_play
    events:
      - sns:
        topicName: response_want_to_play
        displayName: Messages to read from db for want to play command

  is_match_finished:
    handler: is_match_finished.request_is_match_finished
    events:
      - sns:
        topicName: request_is_match_finished
        displayName: Messages to read from slack channel for is current game finished command

  res_is_match_finished:
    handler: res_is_match_finished.response_is_match_finished
    events:
      - sns:
        topicName: response_is_match_finished
        displayName: Messages to read from db for is current game finished command

  current_game:
    handler: current_game.request_current_game
    events:
      - sns:
        topicName: request_current_game
        displayName: Messages to read from slack channel for current game command

  res_current_game:
    handler: res_current_game.response_current_game
    events:
      - sns:
        topicName: response_current_game
        displayName: Messages to read from db for current game command

  neo4j_write:
    handler: neo4j_writer.write


# this setup specifies that the handle_miss_ping function should be run
# when someone acesses the APi Gateway at miss-ping-handler via a POST request
#  index:
#    handler: handler.handle_miss_ping
#    events:
#      - http: POST miss-ping-handler